namespace Kermalis.MIDI;

// Section 2.1
public enum MIDIFormat : ushort
{
	/// <summary>Contains a single multi-channel track</summary>
	Format0,
	/// <summary>Contains one or more simultaneous tracks</summary>
	Format1,
	/// <summary>Contains one or more independent single-track patterns</summary>
	Format2,
}

public enum TimeDivisionType : byte
{
	PPQN,
	SMPTE,
}

public enum SMPTEFormat : byte
{
	Smpte24 = 24,
	Smpte25 = 25,
	Smpte30Drop = 29,
	Smpte30 = 30,
}

/// <summary>Used with <see cref="ControllerMessage"/></summary>
public enum ControllerType : byte
{
	// MSB
	BankSelect,
	ModulationWheel,
	BreathController,
	FootController = 4,
	PortamentoTime,
	DataEntry,
	ChannelVolume,
	Balance,
	Pan = 10,
	ExpressionController,
	EffectControl1,
	EffectControl2,
	GeneralPurposeController1 = 16,
	GeneralPurposeController2,
	GeneralPurposeController3,
	GeneralPurposeController4,
	// LSB
	BankSelectLSB = 32,
	ModulationWheelLSB,
	BreathControllerLSB,
	FootControllerLSB = 36,
	PortamentoTimeLSB,
	DataEntryLSB,
	ChannelVolumeLSB,
	BalanceLSB,
	PanLSB = 42,
	ExpressionControllerLSB,
	EffectControl1LSB,
	EffectControl2LSB,
	GeneralPurposeController1LSB = 48,
	GeneralPurposeController2LSB,
	GeneralPurposeController3LSB,
	GeneralPurposeController4LSB,
	SustainToggle = 64,
	PortamentoToggle,
	SostenutoToggle,
	SoftPedalToggle,
	LegatoToggle,
	Hold2Toggle,
	SoundController1,
	SoundController2,
	SoundController3,
	SoundController4,
	SoundController5,
	SoundController6,
	SoundController7,
	SoundController8,
	SoundController9,
	SoundController10,
	GeneralPurposeController5,
	GeneralPurposeController6,
	GeneralPurposeController7,
	GeneralPurposeController8,
	PortamentoControl,
	HighResolutionVelocityPrefix = 88,
	Effects1Depth = 91,
	Effects2Depth,
	Effects3Depth,
	Effects4Depth,
	Effects5Depth,
	DataIncrement,
	DataDecrement,
	NonRegisteredParameterNumberLSB,
	NonRegisteredParameterNumberMSB,
	RegisteredParameterNumberLSB,
	RegisteredParameterNumberMSB,
	AllSoundOff = 120,
	ResetAllControllers,
	LocalControlToggle,
	AllNotesOff,
	OmniModeOff,
	OmniModeOn,
	MonoModeOn,
	PolyModeOn,
	MAX,
}

/// <summary>Used with <see cref="MetaMessage"/></summary>
public enum MetaMessageType : byte
{
	SequenceNumber, // TODO: Section 3.1 - Must occur at the beginning of the track before any non-zero deltatime
	Text,
	Copyright,
	TrackName,
	InstrumentName,
	Lyric,
	Marker,
	CuePoint,
	ProgramName,
	DeviceName,
	/// <summary>Reserved for ASCII treatment</summary>
	Reserved_A,
	/// <summary>Reserved for ASCII treatment</summary>
	Reserved_B,
	/// <summary>Reserved for ASCII treatment</summary>
	Reserved_C,
	/// <summary>Reserved for ASCII treatment</summary>
	Reserved_D,
	/// <summary>Reserved for ASCII treatment</summary>
	Reserved_E,
	/// <summary>Reserved for ASCII treatment</summary>
	Reserved_F,
	MIDIChannelPrefix = 0x20,
	/// <summary>Not optional</summary>
	EndOfTrack = 0x2F,
	Tempo = 0x51,
	SMPTEOffset = 0x54,
	TimeSignature = 0x58,
	KeySignature,
	ProprietaryEvent = 0x7F,
	MAX,
}
/// <summary>Used with <see cref="MetaMessageType.KeySignature"/></summary>
public enum KeySignatureSF : sbyte
{
	MIN = -8,
	Flat_7 = -7,
	Flat_6 = -6,
	Flat_5 = -5,
	Flat_4 = -4,
	Flat_3 = -3,
	Flat_2 = -2,
	Flat_1 = -1,
	KeyOfC = 0,
	Sharp_1 = +1,
	Sharp_2 = +2,
	Sharp_3 = +3,
	Sharp_4 = +4,
	Sharp_5 = +5,
	Sharp_6 = +6,
	Sharp_7 = +7,
	MAX = +8,
}
/// <summary>Used with <see cref="MetaMessageType.KeySignature"/></summary>
public enum KeySignatureMI : byte
{
	MajorKey,
	MinorKey,
	MAX,
}

/// <summary>Used with <see cref="ProgramChangeMessage"/></summary>
public enum MIDIProgram : byte
{
	AcousticGrandPiano,
	BrightAcousticPiano,
	ElectricGrandPiano,
	HonkyTonkPiano,
	ElectricPiano1,
	ElectricPiano2,
	Harpsichord,
	Clavinet,
	Celesta,
	Glockenspiel,
	MusicBox,
	Vibraphone,
	Marimba,
	Xylophone,
	TubularBells,
	Dulcimer,
	DrawbarOrgan,
	PercussiveOrgan,
	RockOrgan,
	ChurchOrgan,
	ReedOrgan,
	Accordion,
	Harmonica,
	TangoAccordion,
	AcousticGuitarNylon,
	AcousticGuitarSteel,
	ElectricGuitarJazz,
	ElectricGuitarClean,
	ElectricGuitarMuted,
	OverdrivenGuitar,
	DistortionGuitar,
	GuitarHarmonics,
	AcousticBass,
	ElectricBassFinger,
	ElectricBassPick,
	FretlessBass,
	SlapBass1,
	SlapBass2,
	SynthBass1,
	SynthBass2,
	Violin,
	Viola,
	Cello,
	Contrabass,
	TremoloStrings,
	PizzicatoStrings,
	OrchestralHarp,
	Timpani,
	StringEnsemble1,
	StringEnsemble2,
	SynthStrings1,
	SynthStrings2,
	ChoirAahs,
	VoiceOohs,
	SynthVoice,
	OrchestraHit,
	Trumpet,
	Trombone,
	Tuba,
	MutedTrumpet,
	FrenchHorn,
	BrassSection,
	SynthBrass1,
	SynthBrass2,
	SopranoSax,
	AltoSax,
	TenorSax,
	BaritoneSax,
	Oboe,
	EnglishHorn,
	Bassoon,
	Clarinet,
	Piccolo,
	Flute,
	Recorder,
	PanFlute,
	BlownBottle,
	Shakuhachi,
	Whistle,
	Ocarina,
	Lead1Square,
	Lead2Sawtooth,
	Lead3Calliope,
	Lead4Chiff,
	Lead5Charang,
	Lead6Voice,
	Lead7Fifths,
	Lead8BassAndLead,
	Pad1NewAge,
	Pad2Warm,
	Pad3Polysynth,
	Pad4Choir,
	Pad5Bowed,
	Pad6Metallic,
	Pad7Halo,
	Pad8Sweep,
	Fx1Rain,
	Fx2Soundtrack,
	Fx3Crystal,
	Fx4Atmosphere,
	Fx5Brightness,
	Fx6Goblins,
	Fx7Echoes,
	Fx8SciFi,
	Sitar,
	Banjo,
	Shamisen,
	Koto,
	Kalimba,
	BagPipe,
	Fiddle,
	Shanai,
	TinkleBell,
	Agogo,
	SteelDrums,
	Woodblock,
	TaikoDrum,
	MelodicTom,
	SynthDrum,
	ReverseCymbal,
	GuitarFretNoise,
	BreathNoise,
	Seashore,
	BirdTweet,
	TelephoneRing,
	Helicopter,
	Applause,
	Gunshot,
	MAX,
}